site_name: Jenny Website
use_directory_urls: false
docs_dir: gen_docs
nav:
  - Citywalk: citywalk.md
  - Drama: drama.md
  - Music: music.md
  - Podcast: podcast.md
  - Variety: variety.md
theme:
  name: material