site_name: Jenny Website
use_directory_urls: false
docs_dir: gen_docs
nav:
  - Jenny's Tea & Quiet Moments: index.md
  - Music: music.md
  - Page 2: podcast.md
  - relaxation: relaxation.md
theme:
  name: material