site_name: Jenny Website
use_directory_urls: false
docs_dir: gen_docs
nav:
  - Citywalk: citywalk.md
  - Jenny's Tea & Quiet Moments: index.md
  - Music: music.md
  - Podcast: podcast.md
theme:
  name: material